package words

// English is a common-word list inspired by Monkeytype's english wordset.
var English = []string{
	"the", "be", "of", "and", "a", "to", "in", "he", "have", "it",
	"that", "for", "they", "i", "with", "as", "not", "on", "she", "at",
	"by", "this", "we", "you", "do", "but", "from", "or", "which", "one",
	"would", "all", "will", "there", "say", "who", "make", "when", "can", "more",
	"if", "no", "man", "out", "other", "so", "what", "time", "up", "go",
	"about", "than", "into", "could", "state", "only", "new", "year", "some", "take",
	"come", "these", "know", "see", "use", "get", "like", "then", "first", "any",
	"work", "now", "may", "such", "give", "over", "think", "most", "even", "find",
	"day", "also", "after", "way", "many", "must", "look", "before", "great", "back",
	"through", "long", "where", "much", "should", "well", "people", "down", "own", "just",
	"because", "good", "each", "those", "feel", "seem", "how", "high", "too", "place",
	"little", "world", "very", "still", "nation", "hand", "old", "life", "tell", "write",
	"become", "here", "show", "house", "both", "between", "need", "mean", "call", "develop",
	"under", "last", "right", "move", "thing", "general", "school", "never", "same", "another",
	"begin", "while", "number", "part", "turn", "real", "leave", "might", "want", "point",
	"form", "off", "child", "few", "small", "since", "against", "ask", "late", "home",
	"interest", "large", "person", "end", "open", "public", "follow", "during", "present", "without",
	"again", "hold", "govern", "around", "possible", "head", "consider", "word", "program", "problem",
	"however", "lead", "system", "set", "order", "eye", "plan", "run", "keep", "face",
	"fact", "group", "play", "stand", "increase", "early", "course", "change", "help", "line",
	"city", "put", "close", "case", "force", "meet", "once", "water", "upon", "war",
	"far", "north", "power", "night", "ground", "toward", "five", "area", "social", "center",
	"figure", "money", "among", "include", "continue", "whether", "idea", "enough", "across", "white",
	"important", "side", "provide", "though", "young", "example", "door", "experience", "until", "always",
	"result", "month", "question", "study", "car", "walk", "away", "yet", "week", "room",
	"live", "letter", "mother", "answer", "king", "today", "job", "body", "music", "color",
	"black", "short", "book", "level", "type", "value", "class", "fire", "south", "rate",
	"table", "street", "story", "paper", "space", "land", "voice", "light", "mind", "clear",
	"trade", "sure", "road", "court", "image", "town", "love", "art", "true", "history",
	"menu", "sense", "easy", "hard", "fast", "slow", "quiet", "loud", "soft", "strong",
	"free", "full", "half", "next", "near", "above", "below", "inside", "outside", "behind",
	"front", "left", "right", "start", "stop", "finish", "begin", "ready", "wait", "listen",
	"speak", "read", "learn", "teach", "build", "create", "design", "code", "test", "debug",
	"fix", "break", "check", "match", "score", "speed", "focus", "train", "practice", "improve",
	"skill", "habit", "goal", "dream", "hope", "trust", "share", "bring", "carry", "reach",
	"touch", "press", "click", "type", "write", "draw", "paint", "sing", "dance", "smile",
	"laugh", "cry", "sleep", "wake", "eat", "drink", "cook", "clean", "wash", "wear",
	"buy", "sell", "pay", "cost", "save", "spend", "count", "add", "grow", "fall",
	"rise", "raise", "drop", "pick", "choose", "decide", "agree", "deny", "accept", "refuse",
	"allow", "permit", "forbid", "require", "expect", "prefer", "enjoy", "hate", "fear", "worry",
	"relax", "rest", "travel", "visit", "return", "arrive", "depart", "enter", "exit", "escape",
	"search", "seek", "find", "lose", "win", "fail", "try", "attempt", "succeed", "achieve",
}
